name: Build and deploy docs
on: push
#on:
#  push:
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  build-and-deploy:
    name: Deploying docs to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js v13.x
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Install and build
        run: |
          npm install
          npm run bootstrap
          npm run build
          npm run docs:build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          REPOSITORY_NAME: bag-of-tricks/bag-of-tricks.github.io
          BRANCH: main
          FOLDER: docs
          CLEAN: true
